# Generated by Django 6.0.5 on 2026-06-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('texto', models.TextField(blank=True)),
            ],
        ),
    ]
